// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: url_shortener.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_url_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

func (x *ShortenURLRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_url_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLRequest) Reset() {
	*x = GetURLRequest{}
	mi := &file_url_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLRequest) ProtoMessage() {}

func (x *GetURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLRequest.ProtoReflect.Descriptor instead.
func (*GetURLRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetURLRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetURLResponse) Reset() {
	*x = GetURLResponse{}
	mi := &file_url_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetURLResponse) ProtoMessage() {}

func (x *GetURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetURLResponse.ProtoReflect.Descriptor instead.
func (*GetURLResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetURLResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_url_shortener_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_url_shortener_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type FetchApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchApiKeyRequest) Reset() {
	*x = FetchApiKeyRequest{}
	mi := &file_url_shortener_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchApiKeyRequest) ProtoMessage() {}

func (x *FetchApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchApiKeyRequest.ProtoReflect.Descriptor instead.
func (*FetchApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{6}
}

func (x *FetchApiKeyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FetchApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchApiKeyResponse) Reset() {
	*x = FetchApiKeyResponse{}
	mi := &file_url_shortener_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchApiKeyResponse) ProtoMessage() {}

func (x *FetchApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchApiKeyResponse.ProtoReflect.Descriptor instead.
func (*FetchApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{7}
}

func (x *FetchApiKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type DomainMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainMetric) Reset() {
	*x = DomainMetric{}
	mi := &file_url_shortener_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainMetric) ProtoMessage() {}

func (x *DomainMetric) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainMetric.ProtoReflect.Descriptor instead.
func (*DomainMetric) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{8}
}

func (x *DomainMetric) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainMetric) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTopDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDomainsRequest) Reset() {
	*x = GetTopDomainsRequest{}
	mi := &file_url_shortener_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDomainsRequest) ProtoMessage() {}

func (x *GetTopDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDomainsRequest.ProtoReflect.Descriptor instead.
func (*GetTopDomainsRequest) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{9}
}

type GetTopDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopDomains    []*DomainMetric        `protobuf:"bytes,1,rep,name=top_domains,json=topDomains,proto3" json:"top_domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopDomainsResponse) Reset() {
	*x = GetTopDomainsResponse{}
	mi := &file_url_shortener_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopDomainsResponse) ProtoMessage() {}

func (x *GetTopDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortener_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopDomainsResponse.ProtoReflect.Descriptor instead.
func (*GetTopDomainsResponse) Descriptor() ([]byte, []int) {
	return file_url_shortener_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopDomainsResponse) GetTopDomains() []*DomainMetric {
	if x != nil {
		return x.TopDomains
	}
	return nil
}

var File_url_shortener_proto protoreflect.FileDescriptor

const file_url_shortener_proto_rawDesc = "" +
	"\n" +
	"\x13url_shortener.proto\x12\rurl_shortener\x1a\x1cgoogle/api/annotations.proto\"G\n" +
	"\x11ShortenURLRequest\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"1\n" +
	"\x12ShortenURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\",\n" +
	"\rGetURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"+\n" +
	"\x0eGetURLResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\"e\n" +
	"\x11CreateUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"F\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"*\n" +
	"\x12FetchApiKeyRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\".\n" +
	"\x13FetchApiKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"<\n" +
	"\fDomainMetric\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"\x16\n" +
	"\x14GetTopDomainsRequest\"U\n" +
	"\x15GetTopDomainsResponse\x12<\n" +
	"\vtop_domains\x18\x01 \x03(\v2\x1b.url_shortener.DomainMetricR\n" +
	"topDomains2\xa3\x04\n" +
	"\fURLShortener\x12f\n" +
	"\n" +
	"ShortenURL\x12 .url_shortener.ShortenURLRequest\x1a!.url_shortener.ShortenURLResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/shorten\x12[\n" +
	"\x06GetURL\x12\x1c.url_shortener.GetURLRequest\x1a\x1d.url_shortener.GetURLResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/{short_url}\x12d\n" +
	"\n" +
	"CreateUser\x12 .url_shortener.CreateUserRequest\x1a!.url_shortener.CreateUserResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x12n\n" +
	"\vFetchApiKey\x12!.url_shortener.FetchApiKeyRequest\x1a\".url_shortener.FetchApiKeyResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api_key/{email}\x12x\n" +
	"\rGetTopDomains\x12#.url_shortener.GetTopDomainsRequest\x1a$.url_shortener.GetTopDomainsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/metrics/top_domainsB7Z5github.com/alt-coder/url-shortner/url-shortener/protob\x06proto3"

var (
	file_url_shortener_proto_rawDescOnce sync.Once
	file_url_shortener_proto_rawDescData []byte
)

func file_url_shortener_proto_rawDescGZIP() []byte {
	file_url_shortener_proto_rawDescOnce.Do(func() {
		file_url_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)))
	})
	return file_url_shortener_proto_rawDescData
}

var file_url_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_url_shortener_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),     // 0: url_shortener.ShortenURLRequest
	(*ShortenURLResponse)(nil),    // 1: url_shortener.ShortenURLResponse
	(*GetURLRequest)(nil),         // 2: url_shortener.GetURLRequest
	(*GetURLResponse)(nil),        // 3: url_shortener.GetURLResponse
	(*CreateUserRequest)(nil),     // 4: url_shortener.CreateUserRequest
	(*CreateUserResponse)(nil),    // 5: url_shortener.CreateUserResponse
	(*FetchApiKeyRequest)(nil),    // 6: url_shortener.FetchApiKeyRequest
	(*FetchApiKeyResponse)(nil),   // 7: url_shortener.FetchApiKeyResponse
	(*DomainMetric)(nil),          // 8: url_shortener.DomainMetric
	(*GetTopDomainsRequest)(nil),  // 9: url_shortener.GetTopDomainsRequest
	(*GetTopDomainsResponse)(nil), // 10: url_shortener.GetTopDomainsResponse
}
var file_url_shortener_proto_depIdxs = []int32{
	8,  // 0: url_shortener.GetTopDomainsResponse.top_domains:type_name -> url_shortener.DomainMetric
	0,  // 1: url_shortener.URLShortener.ShortenURL:input_type -> url_shortener.ShortenURLRequest
	2,  // 2: url_shortener.URLShortener.GetURL:input_type -> url_shortener.GetURLRequest
	4,  // 3: url_shortener.URLShortener.CreateUser:input_type -> url_shortener.CreateUserRequest
	6,  // 4: url_shortener.URLShortener.FetchApiKey:input_type -> url_shortener.FetchApiKeyRequest
	9,  // 5: url_shortener.URLShortener.GetTopDomains:input_type -> url_shortener.GetTopDomainsRequest
	1,  // 6: url_shortener.URLShortener.ShortenURL:output_type -> url_shortener.ShortenURLResponse
	3,  // 7: url_shortener.URLShortener.GetURL:output_type -> url_shortener.GetURLResponse
	5,  // 8: url_shortener.URLShortener.CreateUser:output_type -> url_shortener.CreateUserResponse
	7,  // 9: url_shortener.URLShortener.FetchApiKey:output_type -> url_shortener.FetchApiKeyResponse
	10, // 10: url_shortener.URLShortener.GetTopDomains:output_type -> url_shortener.GetTopDomainsResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_url_shortener_proto_init() }
func file_url_shortener_proto_init() {
	if File_url_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_url_shortener_proto_rawDesc), len(file_url_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_url_shortener_proto_goTypes,
		DependencyIndexes: file_url_shortener_proto_depIdxs,
		MessageInfos:      file_url_shortener_proto_msgTypes,
	}.Build()
	File_url_shortener_proto = out.File
	file_url_shortener_proto_goTypes = nil
	file_url_shortener_proto_depIdxs = nil
}
